### ISSUE TITLE
whether methylation haplotype load mesure applies to sequencing data where each haplotype within a specific region have different start and end

### ISSUE THREAD

**Issue by taojinsheng** [dinhdiep/MONOD2#2]
Hi Dinh,

I would like to ask you a question.I have bisulfite sequencing data from cfDNA captrued with target probe.Therefore,for a specific region,the haplotypes may have different start and end as follows:
-----------------
 -------------------
  ---------------------
   -----------------------
I wonder whether methylation haplotype load mesure still applies to this kind of data set.Many thanks.

Jinsheng

**Comment by hmyh1202** [comment]
Why no answer ?

**Comment by hmyh1202** [comment]
Why no repley ???
