### ISSUE TITLE
mapping

### ISSUE THREAD

**Issue by hmyh1202** [dinhdiep/MONOD2#3]
could I do alignment with bismark  ?
and use it`s BAM file do methylation haplotype analysis

**Comment by hmyh1202** [comment]
and do methylation haplotype analysis

**Comment by dinhdiep** [comment]
Yes BisMark alignment files will work for this.

**Comment by hmyh1202** [comment]
However, in the script of getHaplo_PE_cgOnly.pl
it wroted that $alignment{"orientation"} = $tmp[1] & 16 ? "C":"W"; in sub getAlignmentInfo

if not suit for Bismark, for its different flag

**Comment by hmyh1202** [comment]
As I know that the orientation for 99 or 163 is W, and 83 or 147 is C strand

**Comment by dinhdiep** [comment]
That statement will be true (results in "C") for 83 and 147 but false
(results in "W") for 99 and 163.

**Comment by hmyh1202** [comment]
So how adjust that for Bismark?

**Comment by dinhdiep** [comment]
Sorry for the confusion, MONOD2/ng.3805/MONOD_analysis_scripts/bam2hapinfo.pl was a previous version that was not compatible with Bismark. You should use getHaplo_PE_cgOnly.pl instead.

**Comment by hmyh1202** [comment]
OK, thanks for your repley. I will use getHaplo_PE_cgOnly.pl instead to call MLB.
Finally, is that code of $alignment{"orientation"} = $tmp[1] & 16 ? "C":"W"; in sub getAlignmentInfo is suit for Bismark  and many other BAM format ? More explain that will be better, for MONOD2 not only for output of BisReadMapper now.

However, I have modified that code as : 
![default](https://user-images.githubusercontent.com/18067365/33407268-880e49b0-d5ab-11e7-821e-510183375eb5.png). was it right for SAM format file of Bismark ?

Excuse me for interrupting you again，
The Best!

**Comment by dinhdiep** [comment]
Yes, this code works for any bam file that follows the current SAM flags
format.

~ Dinh

**Comment by hmyh1202** [comment]
Many Thanks！ @dinhdiep

**Comment by taojinsheng** [comment]
I agree with hmyh1202,I think the getHaplo_PE_cgOnly.pl script for now cannot deal with the bam file generated by Bismark for the reason which the author of bismark noted in FelixKrueger/Bismark#151.
