### ISSUE TITLE
requirement for hapInfo_maskSNPs2mld_block ?

### ISSUE THREAD

**Issue by hmyh1202** [dinhdiep/MONOD2#8]
Hello:
  What is the type of SNP file,  1-based ? come from WGS data or BS-seq data ?
  And how to do quality control for that SNP data, such as 4x depth and so on.

**Comment by dinhdiep** [comment]
I’ve uploaded the SNP location file in parts to the data folder of v2. Its
just the locations from dbSNP concerted to BED format.
